var ufcracedata = [
  {
    "Total (hrs)": 1006.88,
    "YEAR": 2022,
    "Captain wt name": "Twobeers",
    "Crew wt name": "Morsailesed",
    "3rd wt name": "",
    "Given Name/s": "Jeff Linton and Jahn Tihansky",
    "C#": "C4",
    "Group": "Double",
    "Group/Gender": "Double Male",
    "BOAT": "Spawn' OH Rodgers sloop",
    "S1": 56.25,
    "S2": 95.50,
    "S3": 134.52,
    "S4": 351.38,
    "Boat Description": "Tampa Bay 22"
  },
  {
    "Total (hrs)": 1263.68,
    "YEAR": 2020,
    "Captain wt name": "Lrock",
    "Crew wt name": "Yetti",
    "3rd wt name": "Leviosauresrex",
    "Given Name/s": "Larry Ferber and Zack Panetti and Levi Ferber",
    "C#": "C5",
    "Group": "Triple",
    "Group/Gender": "Triple",
    "BOAT": "Nacra Carbon 20",
    "S1": 106.42,
    "S2": 153.22,
    "S3": 204.15,
    "S4": 389.60,
    "Boat Description": "This is a Nacra Carbon 20 NON FOILING beach cat with curved dagger-boards and a spinnaker. We plan to start ~ early am 3/4/20 and plan to continue on to the UF 1200 shooting to meet with the start 7 am 3/7/20. We plan to use an aluminum Grumman canoe +/- sail across the top."
  },
  {
    "Total (hrs)": 1347.28,
    "YEAR": 2016,
    "Captain wt name": "Lrock",
    "Crew wt name": "Crazyrussian",
    "3rd wt name": "",
    "Given Name/s": "Larry Ferber and Vladimir Eremeev",
    "C#": "C5",
    "Group": "Double",
    "Group/Gender": "Double Male",
    "BOAT": "Nacra I-20",
    "S1": 101.35,
    "S2": 174.55,
    "S3": 226.17,
    "S4": 413.28,
    "Boat Description": "No Description Given"
  },
  {
    "Total (hrs)": 1369.60,
    "YEAR": 2006,
    "Captain wt name": "Wizard",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Matt Layden",
    "C#": "C4",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Matt Layden Paradox",
    "S1": 77.92,
    "S2": 159.68,
    "S3": 227.33,
    "S4": 435.75,
    "Boat Description": "Experimental 12' light coastal cruiser"
  },
  {
    "Total (hrs)": 1376.65,
    "YEAR": 2016,
    "Captain wt name": "Sos",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Alan Stewart",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "homemade sailing canoe 18'",
    "S1": 89.10,
    "S2": 177.58,
    "S3": 254.12,
    "S4": 412.45,
    "Boat Description": "New B&B sailing canoe from the racing division."
  },
  {
    "Total (hrs)": 1433.22,
    "YEAR": 2006,
    "Captain wt name": "Manitoucruiser",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Mark Przedwojewski",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 100.67,
    "S2": 177.25,
    "S3": 258.17,
    "S4": 433.50,
    "Boat Description": "Sea Wind # 42 Built by Verlen Kruger BOSS Portage rig known"
  },
  {
    "Total (hrs)": 1438.45,
    "YEAR": 2006,
    "Captain wt name": "Sharkchow",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Warren Richey",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Current Designs Solstice",
    "S1": 100.67,
    "S2": 183.68,
    "S3": 273.13,
    "S4": 418.17,
    "Boat Description": "Current Designs Solstice"
  },
  {
    "Total (hrs)": 1502.45,
    "YEAR": 2010,
    "Captain wt name": "Manitoucruiser",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Mark Przedwojewski",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 83.33,
    "S2": 192.82,
    "S3": 287.00,
    "S4": 439.17,
    "Boat Description": "Sea Wind #42 BOSS 38"
  },
  {
    "Total (hrs)": 1534.58,
    "YEAR": 2010,
    "Captain wt name": "Whitecaps",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Toby Nipper",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 89.33,
    "S2": 184.92,
    "S3": 287.00,
    "S4": 464.08,
    "Boat Description": "kruger seawind"
  },
  {
    "Total (hrs)": 1560.13,
    "YEAR": 2010,
    "Captain wt name": "Wizard",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Matt Layden",
    "C#": "C4",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Matt Layden Elusion",
    "S1": 96.42,
    "S2": 175.67,
    "S3": 295.38,
    "S4": 476.67,
    "Boat Description": "Experimental minimum cruiser, 9' x 38\", enclosed cockpit, self-righting. Efficient & low-stress but not real fast."
  },
  {
    "Total (hrs)": 1680.77,
    "YEAR": 2014,
    "Captain wt name": "Jarhead",
    "Crew wt name": "Leatherlungs",
    "3rd wt name": "",
    "Given Name/s": "Bill Fite and Neil Calore",
    "C#": "C4",
    "Group": "Double",
    "Group/Gender": "Double Male",
    "BOAT": "Sea Pearl",
    "S1": 72.13,
    "S2": 201.28,
    "S3": 307.67,
    "S4": 537.40,
    "Boat Description": "21'black hull cat ketch Moon Shadow; Kruger Sea Wind partially decked 17' canoe"
  },
  {
    "Total (hrs)": 1704.48,
    "YEAR": 2016,
    "Captain wt name": "Bustedrudder",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Bob Waters",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kayak",
    "S1": 132.47,
    "S2": 222.78,
    "S3": 322.67,
    "S4": 490.10,
    "Boat Description": "OysterBar edition 18x or Kayakpro Marlin"
  },
  {
    "Total (hrs)": 1788.13,
    "YEAR": 2012,
    "Captain wt name": "Sos",
    "Crew wt name": "Sandybottom",
    "3rd wt name": "",
    "Given Name/s": "Dawn Stewart and Alan Stewart",
    "C#": "C5",
    "Group": "Double",
    "Group/Gender": "Double Mixed",
    "BOAT": "homemade trimaran 22",
    "S1": 133.12,
    "S2": 250.20,
    "S3": 317.25,
    "S4": 530.45,
    "Boat Description": "#N/A"
  },
  {
    "Total (hrs)": 1892.75,
    "YEAR": 2010,
    "Captain wt name": "Crazyrussian",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Vladimir Eremeev",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Inflatable Catamaran",
    "S1": 119.42,
    "S2": 225.00,
    "S3": 340.75,
    "S4": 585.08,
    "Boat Description": "My old trusty “The Ugly Duckling” – folding inflatable catamaran, 15 x 6.5 ft, 100 sq ft sail area, 170 lbs. I've tried to trash the thing unsuccessfully last 18 years to get rid of it, I guess, I should surrender and use this floating airbed again."
  },
  {
    "Total (hrs)": 1903.37,
    "YEAR": 2016,
    "Captain wt name": "Jarhead",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Bill Fite",
    "C#": "C4",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Sea Pearl",
    "S1": 107.10,
    "S2": 233.13,
    "S3": 351.02,
    "S4": 584.37,
    "Boat Description": "Sea Pearl 21"
  },
  {
    "Total (hrs)": 1925.83,
    "YEAR": 2016,
    "Captain wt name": "Doooobrd",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Donald Polakovics",
    "C#": "C4",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Paul Gartside Blue Skies",
    "S1": 154.00,
    "S2": 247.45,
    "S3": 350.15,
    "S4": 560.47,
    "Boat Description": "Modified Paul Gartside Blue Skies design"
  },
  {
    "Total (hrs)": 1964.88,
    "YEAR": 2012,
    "Captain wt name": "Mosquitomagnet",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Wayne Albert",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Nigel Foster Silhouette",
    "S1": 134.87,
    "S2": 257.05,
    "S3": 373.28,
    "S4": 567.23,
    "Boat Description": "NFD Silhoutte"
  },
  {
    "Total (hrs)": 2018.58,
    "YEAR": 2006,
    "Captain wt name": "Doooobrd",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Donald Polakovics",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Feathercraft K-1",
    "S1": 137.75,
    "S2": 254.83,
    "S3": 393.50,
    "S4": 590.00,
    "Boat Description": "Feathercraft K-1 with Pacific Action Sail"
  },
  {
    "Total (hrs)": 2030.53,
    "YEAR": 2006,
    "Captain wt name": "Pelican",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Nick Hall",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 145.50,
    "S2": 259.17,
    "S3": 395.58,
    "S4": 590.00,
    "Boat Description": "Kruger SeaWind with Hobie Mirage Pedal Drive and Balogh sail and outrigger system."
  },
  {
    "Total (hrs)": 2063.70,
    "YEAR": 2012,
    "Captain wt name": "Riverslayer",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Rod Price",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Superior Expedition Canoe",
    "S1": 155.77,
    "S2": 274.35,
    "S3": 393.95,
    "S4": 585.83,
    "Boat Description": "17'6\" Superior Expedition Canoe"
  },
  {
    "Total (hrs)": 2063.82,
    "YEAR": 2012,
    "Captain wt name": "Whale",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Bill Whale",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Dreamcatcher",
    "S1": 155.80,
    "S2": 274.37,
    "S3": 393.97,
    "S4": 585.88,
    "Boat Description": "Kruger Dreamcatcher"
  },
  {
    "Total (hrs)": 2111.17,
    "YEAR": 2016,
    "Captain wt name": "Microtom",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Tom Dyll",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Dreamcatcher",
    "S1": 174.03,
    "S2": 278.80,
    "S3": 398.70,
    "S4": 584.37,
    "Boat Description": "Kruger Dreamcatcher with a FEKS 1M."
  },
  {
    "Total (hrs)": 2143.58,
    "YEAR": 2010,
    "Captain wt name": "Runningmouth",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Jonathan Coble",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 157.83,
    "S2": 297.75,
    "S3": 413.25,
    "S4": 612.17,
    "Boat Description": "Kruger Sea Wind with PAS and BSD"
  },
  {
    "Total (hrs)": 2187.43,
    "YEAR": 2010,
    "Captain wt name": "Snorebringgator",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Bill Herrmann",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Dreamcatcher",
    "S1": 161.37,
    "S2": 297.92,
    "S3": 418.00,
    "S4": 631.20,
    "Boat Description": "DreamCatcher with Balogh Rig"
  },
  {
    "Total (hrs)": 2200.40,
    "YEAR": 2018,
    "Captain wt name": "Bacon",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Randy Smith",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 127.83,
    "S2": 270.78,
    "S3": 417.27,
    "S4": 659.18,
    "Boat Description": "Kruger Sea Wind"
  },
  {
    "Total (hrs)": 2236.43,
    "YEAR": 2006,
    "Captain wt name": "Drkayak",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Leon Mathis",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 168.55,
    "S2": 294.25,
    "S3": 421.50,
    "S4": 642.58,
    "Boat Description": "Kruger Seawind hopefully with Balough Batwing sail. Seawind Twoten"
  },
  {
    "Total (hrs)": 2259.27,
    "YEAR": 2006,
    "Captain wt name": "Sandybottom",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Dawn Stewart",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Female",
    "BOAT": "Kruger Dreamcatcher",
    "S1": 168.55,
    "S2": 295.75,
    "S3": 442.83,
    "S4": 642.58,
    "Boat Description": "Kruger Dreamcatcher with downwind sail"
  },
  {
    "Total (hrs)": 2593.85,
    "YEAR": 2018,
    "Captain wt name": "Hiawashe",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Judy Perkins",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Female",
    "BOAT": "QCC 500X",
    "S1": 170.35,
    "S2": 334.72,
    "S3": 510.00,
    "S4": 751.23,
    "Boat Description": "QCC 500X with a Falcon Sail"
  },
  {
    "Total (hrs)": 2950.73,
    "YEAR": 2020,
    "Captain wt name": "Misterc",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Mark Cecil",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Tiderace Pace 18",
    "S1": 182.67,
    "S2": 350.58,
    "S3": 536.30,
    "S4": 870.45,
    "Boat Description": "TideRace Pace 18"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2006,
    "Captain wt name": "Alaskanseahorse",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Gregg Berman",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Current Design Stratus 18",
    "S1": 168.02,
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Current Designs Stratus. As no boat can do it all I've found this boat to be excellent in it's abitlity for speed and allowing you to sit in a racing position. However it also lets you switch seating positions easily when the seas get bigger and you find a need for more stability and control."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2006,
    "Captain wt name": "Thereandbackagain",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Charles Colvin",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Current Designs Solstice",
    "S1": 168.02,
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "I'm not 100% sure but something new for me."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2006,
    "Captain wt name": "Wayfarer",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Marek Uliasz",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Sea Wind #127 Pacific Action sail inline skates for portage"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2010,
    "Captain wt name": "Chief",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Steven Isaac",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Dreamcatcher",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "My faithful Dreamcatcher with Balogh BOSS."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2010,
    "Captain wt name": "Pelican",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Nick Hall",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Hobie TI",
    "S1": 148.10,
    "S2": 249.58,
    "S3": 350.50,
    "S4": "#N/A",
    "Boat Description": "Tandem pedal assisted sailing kayak"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2012,
    "Captain wt name": "Ardieo",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Ardie Olson",
    "C#": "C2",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "?",
    "S1": 131.28,
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "21' L x 19.5\" W"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2012,
    "Captain wt name": "Dolphingal",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Kathy Kenley",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Female",
    "BOAT": "Kayakpro Nemo",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Either my Nemo (red-orange) or Impulse (black), with PAS or similar and lots of prayers to Njord, Aeolus,and all other good wind gods."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2012,
    "Captain wt name": "Jollyroger",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Roger Mann",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "homemade trimaran 24",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "XRT Canoe, -Experimental Expedition Racing Trimaran. 24'x14', 4'folded, 30\" for road portage. Wood and glass. Big 16 watertribe amas. 325 lbs empty, 29 day supplies and equip- 125 lbs. Sailing weight 650 lbs."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2012,
    "Captain wt name": "Pelican",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Nick Hall",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Hobie AI",
    "S1": 226.57,
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Hobie AI"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2012,
    "Captain wt name": "Saltyfrog",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Marty Sullivan",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "kayak",
    "S1": 155.25,
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "17.5' stitch-and-glue"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2012,
    "Captain wt name": "Sewsew",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Randy Smyth",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Sizzor",
    "S1": 125.55,
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Sizzor is a 21' Trimaran self built for the Ultimate Florida Challenge. Astrix is my river boat, a class 1 kayak, 18' x 21\"."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2014,
    "Captain wt name": "Chief",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Steven Isaac",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Hobie AI",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Hobie AI"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2016,
    "Captain wt name": "Ardieo",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Ardie Olson",
    "C#": "C2",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "kayak",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Kayak No Sail"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2016,
    "Captain wt name": "Wildblue",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Scott Henderson",
    "C#": "C4",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Sirocco 15",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "15' Sailboat very light."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2018,
    "Captain wt name": "Sewsew",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Randy Smyth",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Sizzor",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Trimaran with Hybrid Wing currently being home built for the Ultimate Florida challenge"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2018,
    "Captain wt name": "Swimboy",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "William Highsmith",
    "C#": "C4",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Core Sound 17",
    "S1": 189.90,
    "S2": 244.07,
    "S3": 368.93,
    "S4": "#N/A",
    "Boat Description": "Core Sound 17"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2022,
    "Captain wt name": "Jollyroger",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Roger Mann",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "LiteRace 1X",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "White LiteRace 1X with orca colored amas. Hobie White/Blue/gray main sail, white-jib + spinaker, mirage pedal drive."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2022,
    "Captain wt name": "Trybabytri",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Christian Patrick",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "G-Cat 21",
    "S1": 166.05,
    "S2": 315.78,
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "GCat 21 with reduced sail area for singlehanding"
  },
  {
    "Total (hrs)": "DNS",
    "YEAR": 2012,
    "Captain wt name": "Hairykerry",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Kerry Newell",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "C-1 Canoe",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "C-1, 17'6\" length, 32 \" beam"
  },
  {
    "Total (hrs)": "DNS",
    "YEAR": 2016,
    "Captain wt name": "Jollyroger",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Roger Mann",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "homemade trimaran 20",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Homebuilt Trimaran. 20 x 18."
  },
  {
    "Total (hrs)": "DNS",
    "YEAR": 2020,
    "Captain wt name": "Jollyroger",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Roger Mann",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "LiteRace 1X",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "LiteRace 1X-360 carbon- added amas, 360 rotating soft shape shifting WingSail 5.8 with reefs. pedal drive. 140 lbs. 19’7” x 10’ white+ black hulls. blue + yellow sail. (Hull self draining + similar to international sailing canoe)"
  }
];