var ufcracedata = [
  {
    "Total (hrs)": 369.23,
    "YEAR": 2022,
    "Captain wt name": "Twobeers",
    "Crew wt name": "Morsailesed",
    "3rd wt name": "",
    "Given Name/s": "Jeff Linton and Jahn Tihansky",
    "C#": "C4",
    "Group": "Double",
    "Group/Gender": "Double Male",
    "BOAT": "Spawn' OH Rodgers sloop",
    "S1": 56.25,
    "S2": 39.25,
    "S3": 39.02,
    "S4": 216.87,
    "Boat Description": "Tampa Bay 22"
  },
  {
    "Total (hrs)": 410.30,
    "YEAR": 2020,
    "Captain wt name": "Lrock",
    "Crew wt name": "Yetti",
    "3rd wt name": "Leviosauresrex",
    "Given Name/s": "Larry Ferber and Zack Panetti and Levi Ferber",
    "C#": "C5",
    "Group": "Triple",
    "Group/Gender": "Triple",
    "BOAT": "Nacra Carbon 20",
    "S1": 106.42,
    "S2": 46.80,
    "S3": 50.93,
    "S4": 185.45,
    "Boat Description": "This is a Nacra Carbon 20 NON FOILING beach cat with curved dagger-boards and a spinnaker. We plan to start ~ early am 3/4/20 and plan to continue on to the UF 1200 shooting to meet with the start 7 am 3/7/20. We plan to use an aluminum Grumman canoe +/- sail across the top."
  },
  {
    "Total (hrs)": 431.93,
    "YEAR": 2016,
    "Captain wt name": "Lrock",
    "Crew wt name": "Crazyrussian",
    "3rd wt name": "",
    "Given Name/s": "Larry Ferber and Vladimir Eremeev",
    "C#": "C5",
    "Group": "Double",
    "Group/Gender": "Double Male",
    "BOAT": "Nacra I-20",
    "S1": 101.35,
    "S2": 73.20,
    "S3": 51.62,
    "S4": 187.12,
    "Boat Description": "No Description Given"
  },
  {
    "Total (hrs)": 443.40,
    "YEAR": 2016,
    "Captain wt name": "Sos",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Alan Stewart",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "homemade sailing canoe 18'",
    "S1": 89.10,
    "S2": 88.48,
    "S3": 76.53,
    "S4": 158.33,
    "Boat Description": "New B&B sailing canoe from the racing division."
  },
  {
    "Total (hrs)": 462.80,
    "YEAR": 2006,
    "Captain wt name": "Sharkchow",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Warren Richey",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Current Designs Solstice",
    "S1": 100.67,
    "S2": 83.02,
    "S3": 89.45,
    "S4": 145.03,
    "Boat Description": "Current Designs Solstice"
  },
  {
    "Total (hrs)": 463.63,
    "YEAR": 2006,
    "Captain wt name": "Manitoucruiser",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Mark Przedwojewski",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 100.67,
    "S2": 76.58,
    "S3": 80.92,
    "S4": 175.33,
    "Boat Description": "Sea Wind # 42 Built by Verlen Kruger BOSS Portage rig known"
  },
  {
    "Total (hrs)": 468.92,
    "YEAR": 2006,
    "Captain wt name": "Wizard",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Matt Layden",
    "C#": "C4",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Matt Layden Paradox",
    "S1": 77.92,
    "S2": 81.77,
    "S3": 67.65,
    "S4": 208.42,
    "Boat Description": "Experimental 12' light coastal cruiser"
  },
  {
    "Total (hrs)": 500.13,
    "YEAR": 2010,
    "Captain wt name": "Manitoucruiser",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Mark Przedwojewski",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 83.33,
    "S2": 109.48,
    "S3": 94.18,
    "S4": 152.17,
    "Boat Description": "Sea Wind #42 BOSS 38"
  },
  {
    "Total (hrs)": 509.25,
    "YEAR": 2010,
    "Captain wt name": "Whitecaps",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Toby Nipper",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 89.33,
    "S2": 95.58,
    "S3": 102.08,
    "S4": 177.08,
    "Boat Description": "kruger seawind"
  },
  {
    "Total (hrs)": 516.00,
    "YEAR": 2010,
    "Captain wt name": "Wizard",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Matt Layden",
    "C#": "C4",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Matt Layden Elusion",
    "S1": 96.42,
    "S2": 79.25,
    "S3": 119.72,
    "S4": 181.28,
    "Boat Description": "Experimental minimum cruiser, 9' x 38\", enclosed cockpit, self-righting. Efficient & low-stress but not real fast."
  },
  {
    "Total (hrs)": 536.47,
    "YEAR": 2016,
    "Captain wt name": "Bustedrudder",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Bob Waters",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kayak",
    "S1": 132.47,
    "S2": 90.32,
    "S3": 99.88,
    "S4": 167.43,
    "Boat Description": "OysterBar edition 18x or Kayakpro Marlin"
  },
  {
    "Total (hrs)": 557.12,
    "YEAR": 2012,
    "Captain wt name": "Sos",
    "Crew wt name": "Sandybottom",
    "3rd wt name": "",
    "Given Name/s": "Dawn Stewart and Alan Stewart",
    "C#": "C5",
    "Group": "Double",
    "Group/Gender": "Double Mixed",
    "BOAT": "homemade trimaran 22",
    "S1": 133.12,
    "S2": 117.08,
    "S3": 67.05,
    "S4": 213.20,
    "Boat Description": "#N/A"
  },
  {
    "Total (hrs)": 562.28,
    "YEAR": 2014,
    "Captain wt name": "Jarhead",
    "Crew wt name": "Leatherlungs",
    "3rd wt name": "",
    "Given Name/s": "Bill Fite and Neil Calore",
    "C#": "C4",
    "Group": "Double",
    "Group/Gender": "Double Male",
    "BOAT": "Sea Pearl",
    "S1": 72.13,
    "S2": 129.15,
    "S3": 106.38,
    "S4": 229.73,
    "Boat Description": "21'black hull cat ketch Moon Shadow; Kruger Sea Wind partially decked 17' canoe"
  },
  {
    "Total (hrs)": 613.77,
    "YEAR": 2016,
    "Captain wt name": "Doooobrd",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Donald Polakovics",
    "C#": "C4",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Paul Gartside Blue Skies",
    "S1": 154.00,
    "S2": 93.45,
    "S3": 102.70,
    "S4": 210.32,
    "Boat Description": "Modified Paul Gartside Blue Skies design"
  },
  {
    "Total (hrs)": 622.50,
    "YEAR": 2010,
    "Captain wt name": "Crazyrussian",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Vladimir Eremeev",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Inflatable Catamaran",
    "S1": 119.42,
    "S2": 105.58,
    "S3": 115.75,
    "S4": 244.33,
    "Boat Description": "My old trusty “The Ugly Duckling” – folding inflatable catamaran, 15 x 6.5 ft, 100 sq ft sail area, 170 lbs. I've tried to trash the thing unsuccessfully last 18 years to get rid of it, I guess, I should surrender and use this floating airbed again."
  },
  {
    "Total (hrs)": 627.75,
    "YEAR": 2016,
    "Captain wt name": "Jarhead",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Bill Fite",
    "C#": "C4",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Sea Pearl",
    "S1": 107.10,
    "S2": 126.03,
    "S3": 117.88,
    "S4": 233.35,
    "Boat Description": "Sea Pearl 21"
  },
  {
    "Total (hrs)": 632.45,
    "YEAR": 2012,
    "Captain wt name": "Mosquitomagnet",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Wayne Albert",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Nigel Foster Silhouette",
    "S1": 134.87,
    "S2": 122.18,
    "S3": 116.23,
    "S4": 193.95,
    "Boat Description": "NFD Silhoutte"
  },
  {
    "Total (hrs)": 640.28,
    "YEAR": 2006,
    "Captain wt name": "Pelican",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Nick Hall",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 145.50,
    "S2": 113.67,
    "S3": 136.42,
    "S4": 194.42,
    "Boat Description": "Kruger SeaWind with Hobie Mirage Pedal Drive and Balogh sail and outrigger system."
  },
  {
    "Total (hrs)": 642.50,
    "YEAR": 2006,
    "Captain wt name": "Doooobrd",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Donald Polakovics",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Feathercraft K-1",
    "S1": 137.75,
    "S2": 117.08,
    "S3": 138.67,
    "S4": 196.50,
    "Boat Description": "Feathercraft K-1 with Pacific Action Sail"
  },
  {
    "Total (hrs)": 653.80,
    "YEAR": 2012,
    "Captain wt name": "Riverslayer",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Rod Price",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Superior Expedition Canoe",
    "S1": 155.77,
    "S2": 118.58,
    "S3": 119.60,
    "S4": 191.88,
    "Boat Description": "17'6\" Superior Expedition Canoe"
  },
  {
    "Total (hrs)": 653.80,
    "YEAR": 2012,
    "Captain wt name": "Whale",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Bill Whale",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Dreamcatcher",
    "S1": 155.80,
    "S2": 118.57,
    "S3": 119.60,
    "S4": 191.92,
    "Boat Description": "Kruger Dreamcatcher"
  },
  {
    "Total (hrs)": 662.58,
    "YEAR": 2010,
    "Captain wt name": "Runningmouth",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Jonathan Coble",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 157.83,
    "S2": 139.92,
    "S3": 115.50,
    "S4": 198.92,
    "Boat Description": "Kruger Sea Wind with PAS and BSD"
  },
  {
    "Total (hrs)": 675.27,
    "YEAR": 2016,
    "Captain wt name": "Microtom",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Tom Dyll",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Dreamcatcher",
    "S1": 174.03,
    "S2": 104.77,
    "S3": 119.90,
    "S4": 185.67,
    "Boat Description": "Kruger Dreamcatcher with a FEKS 1M."
  },
  {
    "Total (hrs)": 678.95,
    "YEAR": 2010,
    "Captain wt name": "Snorebringgator",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Bill Herrmann",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Dreamcatcher",
    "S1": 161.37,
    "S2": 136.55,
    "S3": 120.08,
    "S4": 213.20,
    "Boat Description": "DreamCatcher with Balogh Rig"
  },
  {
    "Total (hrs)": 709.55,
    "YEAR": 2006,
    "Captain wt name": "Drkayak",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Leon Mathis",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 168.55,
    "S2": 125.70,
    "S3": 127.25,
    "S4": 221.08,
    "Boat Description": "Kruger Seawind hopefully with Balough Batwing sail. Seawind Twoten"
  },
  {
    "Total (hrs)": 709.55,
    "YEAR": 2006,
    "Captain wt name": "Sandybottom",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Dawn Stewart",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Female",
    "BOAT": "Kruger Dreamcatcher",
    "S1": 168.55,
    "S2": 127.20,
    "S3": 147.08,
    "S4": 199.75,
    "Boat Description": "Kruger Dreamcatcher with downwind sail"
  },
  {
    "Total (hrs)": 725.33,
    "YEAR": 2018,
    "Captain wt name": "Bacon",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Randy Smith",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": 127.83,
    "S2": 142.95,
    "S3": 146.48,
    "S4": 241.92,
    "Boat Description": "Kruger Sea Wind"
  },
  {
    "Total (hrs)": 827.55,
    "YEAR": 2018,
    "Captain wt name": "Hiawashe",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Judy Perkins",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Female",
    "BOAT": "QCC 500X",
    "S1": 170.35,
    "S2": 164.37,
    "S3": 175.28,
    "S4": 241.23,
    "Boat Description": "QCC 500X with a Falcon Sail"
  },
  {
    "Total (hrs)": 1010.73,
    "YEAR": 2020,
    "Captain wt name": "Misterc",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Mark Cecil",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Tiderace Pace 18",
    "S1": 182.67,
    "S2": 167.92,
    "S3": 185.72,
    "S4": 334.15,
    "Boat Description": "TideRace Pace 18"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2006,
    "Captain wt name": "Alaskanseahorse",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Gregg Berman",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Current Design Stratus 18",
    "S1": 168.02,
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Current Designs Stratus. As no boat can do it all I've found this boat to be excellent in it's abitlity for speed and allowing you to sit in a racing position. However it also lets you switch seating positions easily when the seas get bigger and you find a need for more stability and control."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2006,
    "Captain wt name": "Thereandbackagain",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Charles Colvin",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Current Designs Solstice",
    "S1": 168.02,
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "I'm not 100% sure but something new for me."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2006,
    "Captain wt name": "Wayfarer",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Marek Uliasz",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Seawind",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Sea Wind #127 Pacific Action sail inline skates for portage"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2010,
    "Captain wt name": "Chief",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Steven Isaac",
    "C#": "C3",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Kruger Dreamcatcher",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "My faithful Dreamcatcher with Balogh BOSS."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2010,
    "Captain wt name": "Pelican",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Nick Hall",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Hobie TI",
    "S1": 148.10,
    "S2": 101.48,
    "S3": 100.92,
    "S4": "#N/A",
    "Boat Description": "Tandem pedal assisted sailing kayak"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2012,
    "Captain wt name": "Ardieo",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Ardie Olson",
    "C#": "C2",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "?",
    "S1": 131.28,
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "21' L x 19.5\" W"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2012,
    "Captain wt name": "Dolphingal",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Kathy Kenley",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Female",
    "BOAT": "Kayakpro Nemo",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Either my Nemo (red-orange) or Impulse (black), with PAS or similar and lots of prayers to Njord, Aeolus,and all other good wind gods."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2012,
    "Captain wt name": "Jollyroger",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Roger Mann",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "homemade trimaran 24",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "XRT Canoe, -Experimental Expedition Racing Trimaran. 24'x14', 4'folded, 30\" for road portage. Wood and glass. Big 16 watertribe amas. 325 lbs empty, 29 day supplies and equip- 125 lbs. Sailing weight 650 lbs."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2012,
    "Captain wt name": "Pelican",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Nick Hall",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Hobie AI",
    "S1": 226.57,
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Hobie AI"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2012,
    "Captain wt name": "Saltyfrog",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Marty Sullivan",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "kayak",
    "S1": 155.25,
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "17.5' stitch-and-glue"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2012,
    "Captain wt name": "Sewsew",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Randy Smyth",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Sizzor",
    "S1": 125.55,
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Sizzor is a 21' Trimaran self built for the Ultimate Florida Challenge. Astrix is my river boat, a class 1 kayak, 18' x 21\"."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2014,
    "Captain wt name": "Chief",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Steven Isaac",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Hobie AI",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Hobie AI"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2016,
    "Captain wt name": "Ardieo",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Ardie Olson",
    "C#": "C2",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "kayak",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Kayak No Sail"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2016,
    "Captain wt name": "Wildblue",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Scott Henderson",
    "C#": "C4",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Sirocco 15",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "15' Sailboat very light."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2018,
    "Captain wt name": "Sewsew",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Randy Smyth",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Sizzor",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Trimaran with Hybrid Wing currently being home built for the Ultimate Florida challenge"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2018,
    "Captain wt name": "Swimboy",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "William Highsmith",
    "C#": "C4",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "Core Sound 17",
    "S1": 189.90,
    "S2": 54.17,
    "S3": 124.87,
    "S4": "#N/A",
    "Boat Description": "Core Sound 17"
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2022,
    "Captain wt name": "Jollyroger",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Roger Mann",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "LiteRace 1X",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "White LiteRace 1X with orca colored amas. Hobie White/Blue/gray main sail, white-jib + spinaker, mirage pedal drive."
  },
  {
    "Total (hrs)": "DNF",
    "YEAR": 2022,
    "Captain wt name": "Trybabytri",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Christian Patrick",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "G-Cat 21",
    "S1": 166.05,
    "S2": 149.73,
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "GCat 21 with reduced sail area for singlehanding"
  },
  {
    "Total (hrs)": "DNS",
    "YEAR": 2012,
    "Captain wt name": "Hairykerry",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Kerry Newell",
    "C#": "C1",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "C-1 Canoe",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "C-1, 17'6\" length, 32 \" beam"
  },
  {
    "Total (hrs)": "DNS",
    "YEAR": 2016,
    "Captain wt name": "Jollyroger",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Roger Mann",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "homemade trimaran 20",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "Homebuilt Trimaran. 20 x 18."
  },
  {
    "Total (hrs)": "DNS",
    "YEAR": 2020,
    "Captain wt name": "Jollyroger",
    "Crew wt name": "",
    "3rd wt name": "",
    "Given Name/s": "Roger Mann",
    "C#": "C5",
    "Group": "Single",
    "Group/Gender": "Single Male",
    "BOAT": "LiteRace 1X",
    "S1": "#N/A",
    "S2": "#N/A",
    "S3": "#N/A",
    "S4": "#N/A",
    "Boat Description": "LiteRace 1X-360 carbon- added amas, 360 rotating soft shape shifting WingSail 5.8 with reefs. pedal drive. 140 lbs. 19’7” x 10’ white+ black hulls. blue + yellow sail. (Hull self draining + similar to international sailing canoe)"
  }
];